-- 1. USUARIOS (Padre)
CREATE OR REPLACE TRIGGER TRG_AUDIT_USUARIO
BEFORE INSERT OR UPDATE ON CC_USUARIO FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION := SYSDATE;
    END IF;
    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/

-- 2. EMPLEADOS (Hijo)
CREATE OR REPLACE TRIGGER TRG_AUDIT_EMPLEADO
BEFORE INSERT OR UPDATE ON CC_EMPLEADO FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER; 
        :NEW.FECHA_CREACION := SYSDATE;
    END IF;
    :NEW.USUARIO_MODIFICACION := USER; 
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/

-- 3. ADMINISTRADORES (Hijo)
CREATE OR REPLACE TRIGGER TRG_AUDIT_ADMIN
BEFORE INSERT OR UPDATE ON CC_ADMINISTRADOR FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER; 
        :NEW.FECHA_CREACION := SYSDATE;
    END IF;
    :NEW.USUARIO_MODIFICACION := USER; 
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/

-- 4. Area
CREATE OR REPLACE TRIGGER TRG_AUDIT_AREA
BEFORE INSERT OR UPDATE ON CC_AREA FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER; 
        :NEW.FECHA_CREACION := SYSDATE;
    END IF;
    :NEW.USUARIO_MODIFICACION := USER; 
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/
-- 5. Rol
CREATE OR REPLACE TRIGGER TRG_AUDIT_ROL
BEFORE INSERT OR UPDATE ON CC_ROL FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER; 
        :NEW.FECHA_CREACION := SYSDATE;
    END IF;
    :NEW.USUARIO_MODIFICACION := USER; 
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/
