/* =========================================================
   TRIGGERS DE AUDITORÍA Y VALORES POR DEFECTO
   Aplica para todas las tablas del sistema.
   ========================================================= */

-- Función auxiliar o procedimiento no es necesario, repetimos lógica para asegurar disparadores individuales.

-- 1. USUARIOS (Padre)
CREATE OR REPLACE TRIGGER TRG_AUDIT_USUARIO
BEFORE INSERT OR UPDATE ON CC_USUARIO FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION := SYSDATE;
    END IF;
    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/

-- 2. EMPLEADOS (Hijo)
CREATE OR REPLACE TRIGGER TRG_AUDIT_EMPLEADO
BEFORE INSERT OR UPDATE ON CC_EMPLEADO FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER; 
        :NEW.FECHA_CREACION := SYSDATE;
    END IF;
    :NEW.USUARIO_MODIFICACION := USER; 
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/

-- 3. ADMINISTRADORES (Hijo)
CREATE OR REPLACE TRIGGER TRG_AUDIT_ADMIN
BEFORE INSERT OR UPDATE ON CC_ADMINISTRADOR FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER; 
        :NEW.FECHA_CREACION := SYSDATE;
    END IF;
    :NEW.USUARIO_MODIFICACION := USER; 
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/

-- 4. FONDOS
CREATE OR REPLACE TRIGGER TRG_AUDIT_FONDO
BEFORE INSERT OR UPDATE ON CC_FONDO FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER; 
        :NEW.FECHA_CREACION := SYSDATE;
        :NEW.SALDO_ACTUAL_FONDO := NVL(:NEW.SALDO_ACTUAL_FONDO, 0);
    END IF;
    :NEW.USUARIO_MODIFICACION := USER; 
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/

-- 5. SOLICITUDES DE GASTO
CREATE OR REPLACE TRIGGER TRG_AUDIT_SOLICITUD
BEFORE INSERT OR UPDATE ON CC_SOLICITUD_GASTO FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER; 
        :NEW.FECHA_CREACION := SYSDATE;
        :NEW.MONTO_SOLICITADO := NVL(:NEW.MONTO_SOLICITADO, 0);
    END IF;
    :NEW.USUARIO_MODIFICACION := USER; 
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/

-- 6. TRANSACCIONES
CREATE OR REPLACE TRIGGER TRG_AUDIT_TRANSACCION
BEFORE INSERT OR UPDATE ON CC_TRANSACCION FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER; 
        :NEW.FECHA_CREACION := SYSDATE;
        :NEW.MONTO_TRANSACCION := NVL(:NEW.MONTO_TRANSACCION, 0);
    END IF;
    :NEW.USUARIO_MODIFICACION := USER; 
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/

-- 7. COMPROBANTES DE PAGO (Validación de montos automática)
CREATE OR REPLACE TRIGGER TRG_AUDIT_COMPROBANTE
BEFORE INSERT OR UPDATE ON CC_COMPROBANTE_PAGO FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER; :NEW.FECHA_CREACION := SYSDATE;
        :NEW.MONTO_TOTAL := NVL(:NEW.MONTO_TOTAL, 0);
        :NEW.SUBTOTAL := NVL(:NEW.SUBTOTAL, 0);
        :NEW.IGV := NVL(:NEW.IGV, 0);
    END IF;
    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/

-- 8. RENDICIONES
CREATE OR REPLACE TRIGGER TRG_AUDIT_RENDICION
BEFORE INSERT OR UPDATE ON CC_RENDICION FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER; :NEW.FECHA_CREACION := SYSDATE;
        :NEW.TOTAL_DECLARADO := NVL(:NEW.TOTAL_DECLARADO, 0);
    END IF;
    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/

-- 9. CONTROL AUTOMÁTICO DE HISTORIAL DE JEFATURAS (Log de cambios)
CREATE OR REPLACE TRIGGER TRG_HISTORIAL_JEFES
AFTER INSERT OR UPDATE OF ID_JEFE_DIRECTO ON CC_EMPLEADO
FOR EACH ROW
BEGIN
    -- Cerrar registro actual
    IF UPDATING AND :OLD.ID_JEFE_DIRECTO IS NOT NULL THEN
        UPDATE CC_HISTORIAL_JEFATURA
        SET FECHA_FIN = SYSDATE,
            USUARIO_MODIFICACION = USER,
            FECHA_MODIFICACION = SYSDATE
        WHERE ID_EMPLEADO = :OLD.ID_USUARIO AND FECHA_FIN IS NULL;
    END IF;

    -- Abrir nuevo registro
    INSERT INTO CC_HISTORIAL_JEFATURA (
        ID_HISTORIAL, ID_EMPLEADO, ID_JEFE, FECHA_INICIO, FECHA_REGISTRO, USUARIO_CREACION, FECHA_CREACION
    ) VALUES (
        (SELECT NVL(MAX(ID_HISTORIAL), 0) + 1 FROM CC_HISTORIAL_JEFATURA),
        :NEW.ID_USUARIO, :NEW.ID_JEFE_DIRECTO, SYSDATE, SYSDATE, USER, SYSDATE
    );
END;
/

-- 10. TRIGGERS ADICIONALES PARA TABLAS MAESTRAS
-- Repetir lógica simple para Moneda, Rubro, Area, Rol, Ciclo, CajaChica, EntregaRendir
-- (Abreviado para el ejemplo pero listo para expansión similar)

CREATE OR REPLACE TRIGGER TRG_AUDIT_AREA
BEFORE INSERT OR UPDATE ON CC_AREA FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.USUARIO_CREACION := USER; 
        :NEW.FECHA_CREACION := SYSDATE; 
    END IF;
    :NEW.USUARIO_MODIFICACION := USER; 
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_MONEDA
BEFORE INSERT OR UPDATE ON CC_MONEDA FOR EACH ROW
BEGIN
    IF INSERTING THEN 
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION := SYSDATE; 
    END IF;
    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION := SYSDATE;
END;
/