#!/bin/bash

# Define the absolute path to the database directory
DB_DIR="/Users/gaelarias/Documents/PUCP/2026-1/Programación 3/Economix/TA-1INF30/database"
SCRIPT_UNICO="$DB_DIR/ScriptUnico.sql"

echo "Generating $SCRIPT_UNICO..."

# Clear the ScriptUnico.sql file
> "$SCRIPT_UNICO"

# Add header
echo "-- Consolidated SQL Script for Economix Database" >> "$SCRIPT_UNICO"
echo "-- Generated by generate_script_unico.sh on $(date)" >> "$SCRIPT_UNICO"
echo "" >> "$SCRIPT_UNICO"

# 1. Elimination script (to ensure a clean slate for full recreation)
echo "-- 1. Elimination Script" >> "$SCRIPT_UNICO"
cat "$DB_DIR/General/Eliminacion.sql" >> "$SCRIPT_UNICO"
echo "" >> "$SCRIPT_UNICO"

# 2. Creation script (table definitions)
echo "-- 2. Creation Script" >> "$SCRIPT_UNICO"
cat "$DB_DIR/General/Creacion.sql" >> "$SCRIPT_UNICO"
echo "" >> "$SCRIPT_UNICO"

# 3. Auditoria table and procedures
echo "-- 3. Auditoria Schema and Procedures" >> "$SCRIPT_UNICO"
cat "$DB_DIR/General/Auditoria.sql" >> "$SCRIPT_UNICO"
echo "" >> "$SCRIPT_UNICO"

# 4. Login Attempts procedures
echo "-- 4. Login Attempts Procedures" >> "$SCRIPT_UNICO"
cat "$DB_DIR/General/LoginAttempts.sql" >> "$SCRIPT_UNICO"
echo "" >> "$SCRIPT_UNICO"

# 5. Eventos (if any) - this needs to be before triggers that might use them
echo "-- 5. Eventos (e.g., for CicloRendicion)" >> "$SCRIPT_UNICO"
cat "$DB_DIR/General/EventosCicloRendicion.sql" >> "$SCRIPT_UNICO"
echo "" >> "$SCRIPT_UNICO"

# 6. All Store Procedures (grouped by module for readability, order might matter for dependencies)
echo "-- 6. Store Procedures" >> "$SCRIPT_UNICO"
find "$DB_DIR" -type f -name "*StoreProcedure.sql" ! -path "*RRHH/UsuarioStoreProcedure.sql" ! -path "*RRHH/RolStoreProcedure.sql" ! -path "*RRHH/EmpleadoStoreProcedure.sql" ! -path "*RRHH/AreaStoreProcedure.sql" ! -path "*RRHH/AdministradorStoreProcedure.sql" | sort | while read -r file; do
    echo "-- Adding Store Procedure from: $(basename "$file")" >> "$SCRIPT_UNICO"
    cat "$file" >> "$SCRIPT_UNICO"
    echo "" >> "$SCRIPT_UNICO"
done
# Adding specific RRHH Store Procedures last due to potential dependencies
echo "-- Adding RRHH Store Procedures (ordered for dependencies)" >> "$SCRIPT_UNICO"
cat "$DB_DIR/RRHH/AdministradorStoreProcedure.sql" >> "$SCRIPT_UNICO"; echo "" >> "$SCRIPT_UNICO"
cat "$DB_DIR/RRHH/AreaStoreProcedure.sql" >> "$SCRIPT_UNICO"; echo "" >> "$SCRIPT_UNICO"
cat "$DB_DIR/RRHH/RolStoreProcedure.sql" >> "$SCRIPT_UNICO"; echo "" >> "$SCRIPT_UNICO"
cat "$DB_DIR/RRHH/EmpleadoStoreProcedure.sql" >> "$SCRIPT_UNICO"; echo "" >> "$SCRIPT_UNICO"
cat "$DB_DIR/RRHH/UsuarioStoreProcedure.sql" >> "$SCRIPT_UNICO"; echo "" >> "$SCRIPT_UNICO"

# 7. All Triggers (grouped by module)
echo "-- 7. Triggers" >> "$SCRIPT_UNICO"
find "$DB_DIR" -type f -name "*TriggersAuditoria.sql" | sort | while read -r file; do
    echo "-- Adding Triggers from: $(basename "$file")" >> "$SCRIPT_UNICO"
    cat "$file" >> "$SCRIPT_UNICO"
    echo "" >> "$SCRIPT_UNICO"
done

echo "Finished generating $SCRIPT_UNICO"
