-- =============================================
-- 1. TABLAS MAESTRAS (CATÁLOGOS)
-- =============================================

CREATE TABLE CC_MONEDA (
    ID_MONEDA NUMBER PRIMARY KEY,
    CODIGO_ISO_MONEDA CHAR(3) NOT NULL,
    SIMBOLO_MONEDA VARCHAR2(5) NOT NULL,
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_RUBRO (
    ID_RUBRO NUMBER PRIMARY KEY,
    NOMBRE_RUBRO VARCHAR2(60) NOT NULL,
    DESCRIPCION_RUBRO VARCHAR2(200),
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_AREA (
    ID_AREA NUMBER PRIMARY KEY,
    NOMBRE_AREA VARCHAR2(60) NOT NULL,
    DESCRIPCION_AREA VARCHAR2(200),
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_ROL (
    ID_ROL NUMBER PRIMARY KEY,
    TITULO_ROL VARCHAR2(50) NOT NULL,
    DESCRIPCION_ROL VARCHAR2(200),
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

-- =============================================
-- 2. JERARQUÍA DE USUARIOS
-- =============================================

CREATE TABLE CC_USUARIO (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOMBRES VARCHAR2(60) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(40) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(40),
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    ESTADO_USUARIO VARCHAR2(20) NOT NULL,
    CONSTRAINT CK_ESTADO_USUARIO CHECK (ESTADO_USUARIO IN ('Activo', 'Inactivo')),
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_EMPLEADO (
    ID_USUARIO NUMBER PRIMARY KEY,
    CORREO_INSTITUCIONAL VARCHAR2(100) UNIQUE,
    NUMERO_CELULAR VARCHAR2(15),
    ID_AREA NUMBER,          
    ID_ROL NUMBER,           
    ID_JEFE_DIRECTO NUMBER,
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE,
    CONSTRAINT FK_EMP_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES CC_USUARIO(ID_USUARIO)
);

CREATE TABLE CC_ADMINISTRADOR (
    ID_USUARIO NUMBER PRIMARY KEY,
    CORREO_SOPORTE VARCHAR2(100),
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE,
    CONSTRAINT FK_ADMIN_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES CC_USUARIO(ID_USUARIO)
);

-- =============================================
-- 3. CUENTAS Y RENDICIONES
-- =============================================

CREATE TABLE CC_CUENTA_BANCARIA (
    ID_CUENTA_BANCARIA NUMBER PRIMARY KEY,
    BANCO_CUENTA_BANCARIA VARCHAR2(50) NOT NULL,
    NUMERO_CUENTA_BANCARIA VARCHAR2(30) NOT NULL,
    CCI_CUENTA_BANCARIA CHAR(20),
    ID_MONEDA NUMBER NOT NULL, 
    ES_PRINCIPAL NUMBER(1) DEFAULT 0, 
    ID_EMPLEADO NUMBER,
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_RENDICION (
    ID_RENDICION NUMBER PRIMARY KEY,
    FECHA_PRESENTACION DATE,
    FECHA_APROBACION DATE,
    TOTAL_DECLARADO NUMBER(10,2),
    TOTAL_APROBADO NUMBER(10,2),
    SALDO_FINAL NUMBER(10,2),
    ESTADO_RENDICION VARCHAR2(20) NOT NULL,
    COMENTARIO_RENDICION VARCHAR2(500),
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

-- =============================================
-- 4. FONDOS, CICLOS Y SOLICITUDES
-- =============================================

CREATE TABLE CC_FONDO (
    ID_FONDO NUMBER PRIMARY KEY,
    NOMBRE_FONDO VARCHAR2(100) NOT NULL,
    SALDO_ACTUAL_FONDO NUMBER(10,2),
    ESTADO_FONDO VARCHAR2(20) NOT NULL,
    FECHA_CREACION_FONDO DATE, 
    ID_MONEDA NUMBER NOT NULL,           
    ID_CUENTA_BANCARIA NUMBER,  
    ID_RESPONSABLE NUMBER,
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_CAJA_CHICA (
    ID_FONDO NUMBER PRIMARY KEY,
    MONTO_TECHO_CAJA_CHICA NUMBER(10,2) NOT NULL,
    ID_AREA NUMBER,
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_ENTREGA_RENDIR (
    ID_FONDO NUMBER PRIMARY KEY,
    MOTIVO_ENTREGA_RENDIR VARCHAR2(200),
    MONTO_SOLICITADO NUMBER(10,2),
    FECHA_SOLICITUD DATE,
    FECHA_APERTURA DATE,
    FECHA_CIERRE DATE,
    ESTADO_ENTREGA VARCHAR2(20),
    ID_SOLICITANTE NUMBER,       
    ID_APROBADOR NUMBER,
    ID_RENDICION NUMBER, 
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_CICLO_CAJA (
    ID_CICLO_CAJA NUMBER PRIMARY KEY,
    NUMERO_SEMANA NUMBER,
    FECHA_APERTURA DATE NOT NULL,
    FECHA_CIERRE DATE,
    MONTO_TECHO_CICLO NUMBER(10,2),
    SALDO_INICIAL_CICLO NUMBER(10,2),
    TOTAL_GASTADO_CICLO NUMBER(10,2),
    ESTADO_CICLO_CAJA VARCHAR2(20),
    ID_CAJA_CHICA NUMBER NOT NULL,
    ID_RENDICION NUMBER,
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_SOLICITUD_GASTO (
    ID_SOLICITUD_GASTO NUMBER PRIMARY KEY,
    FECHA_SOLICITUD DATE, 
    MONTO_SOLICITADO NUMBER(10,2) NOT NULL,
    MOTIVO_SOLICITUD VARCHAR2(200),
    ESTADO_SOLICITUD VARCHAR2(20),
    ID_SOLICITANTE NUMBER NOT NULL,       
    ID_DESTINATARIO NUMBER,
    ID_CICLO_CAJA NUMBER,
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_COMPROBANTE_PAGO (
    ID_COMPROBANTE NUMBER PRIMARY KEY,
    TIPO_DOCUMENTO VARCHAR2(20) NOT NULL,
    RUC_PROVEEDOR CHAR(11),
    RAZON_SOCIAL VARCHAR2(150),
    NUMERO_SERIE VARCHAR2(30),
    FECHA_EMISION DATE,
    MONTO_TOTAL NUMBER(10,2),
    SUBTOTAL NUMBER(10,2),
    IGV NUMBER(10,2),
    ARCHIVO_ADJUNTO VARCHAR2(255),
    ID_SOLICITUD_GASTO NUMBER,   
    ID_ENTREGA_RENDIR NUMBER,    
    ID_RUBRO NUMBER,             
    ID_MONEDA NUMBER,
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_TRANSACCION (
    ID_TRANSACCION NUMBER PRIMARY KEY,
    TIPO_OPERACION VARCHAR2(30) NOT NULL,
    FECHA_OPERACION DATE,
    MONTO_TRANSACCION NUMBER(10,2) NOT NULL,
    NUMERO_OPERACION_BANCARIA VARCHAR2(30),
    MEDIO_PAGO VARCHAR2(30),
    TIPO_CAMBIO NUMBER(10,4),
    ID_CUENTA_ORIGEN NUMBER,     
    ID_CUENTA_DESTINO NUMBER,    
    ID_MONEDA NUMBER,
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_HISTORIAL_JEFATURA (
    ID_HISTORIAL NUMBER PRIMARY KEY,
    ID_EMPLEADO NUMBER NOT NULL,
    ID_JEFE NUMBER,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    FECHA_REGISTRO DATE,
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);