-- =============================================
-- 1. TABLAS MAESTRAS (CATÁLOGOS)
-- =============================================

CREATE TABLE CC_MONEDA (
    ID_MONEDA NUMBER PRIMARY KEY,
    CODIGO_ISO_MONEDA CHAR(3),        -- PEN, USD
    SIMBOLO_MONEDA VARCHAR2(5),       -- S/. , $
    -- Auditoría
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_RUBRO (
    ID_RUBRO NUMBER PRIMARY KEY,
    NOMBRE_RUBRO VARCHAR2(60),
    DESCRIPCION_RUBRO VARCHAR2(200),
    -- Auditoría
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_AREA (
    ID_AREA NUMBER PRIMARY KEY,
    NOMBRE_AREA VARCHAR2(60),
    DESCRIPCION_AREA VARCHAR2(200),
    -- Auditoría
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_ROL (
    ID_ROL NUMBER PRIMARY KEY,
    TITULO_ROL VARCHAR2(50),
    DESCRIPCION_ROL VARCHAR2(200),
    -- Auditoría
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

-- =============================================
-- 2. ACTORES Y CUENTAS
-- =============================================

CREATE TABLE CC_EMPLEADO (
    ID_EMPLEADO NUMBER PRIMARY KEY,
    NOMBRES_EMPLEADO VARCHAR2(60),
    APELLIDO_PATERNO_EMPLEADO VARCHAR2(40),
    APELLIDO_MATERNO_EMPLEADO VARCHAR2(40),
    CORREO_INSTITUCIONAL_EMPLEADO VARCHAR2(100),
    NUMERO_CELULAR_EMPLEADO VARCHAR2(15),
    ID_AREA NUMBER,          
    ID_ROL NUMBER,           
    ID_JEFE_DIRECTO NUMBER,  
    -- Auditoría
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_CUENTA_BANCARIA (
    ID_CUENTA_BANCARIA NUMBER PRIMARY KEY,
    BANCO_CUENTA_BANCARIA VARCHAR2(50),
    NUMERO_CUENTA_BANCARIA VARCHAR2(30),
    CCI_CUENTA_BANCARIA CHAR(20),
    
    ID_MONEDA NUMBER, 
    
    ES_CUENTA_BANCARIA_PRINCIPAL NUMBER(1) DEFAULT 0, 
    ID_EMPLEADO NUMBER,      
    -- Auditoría
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);
CREATE TABLE CC_HISTORIAL_JEFATURA (
    ID_HISTORIAL NUMBER,
    ID_EMPLEADO NUMBER NOT NULL,
    ID_JEFE NUMBER,         -- Puede ser NULL si es Gerente General
    FECHA_INICIO DATE DEFAULT SYSDATE,
    FECHA_FIN DATE,         -- NULL indica que es el jefe actual
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

-- =============================================
-- 3. RENDICIÓN (DESTINO FINAL)
-- =============================================

CREATE TABLE CC_RENDICION (
    ID_RENDICION NUMBER PRIMARY KEY,
    FECHA_PRESENTACION DATE,
    FECHA_APROBACION DATE,
    TOTAL_DECLARADO NUMBER(10,2),
    TOTAL_APROBADO NUMBER(10,2),
    SALDO_FINAL NUMBER(10,2),
    ESTADO_RENDICION VARCHAR2(20),
    COMENTARIO_RENDICION VARCHAR2(500),
    -- Auditoría
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

-- =============================================
-- 4. ESTRUCTURA DE FONDOS (PADRE E HIJOS)
-- =============================================

CREATE TABLE CC_FONDO (
    ID_FONDO NUMBER PRIMARY KEY,
    NOMBRE_FONDO VARCHAR2(100),
    SALDO_ACTUAL_FONDO NUMBER(10,2),
    ESTADO_FONDO VARCHAR2(20),
    FECHA_CREACION_FONDO DATE DEFAULT SYSDATE, 
    ID_MONEDA NUMBER,           
    ID_CUENTA_BANCARIA NUMBER,  
    ID_RESPONSABLE NUMBER,      
    -- Auditoría
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_CAJA_CHICA (
    ID_FONDO NUMBER PRIMARY KEY, 
    MONTO_TECHO_CAJA_CHICA NUMBER(10,2),
    ID_AREA NUMBER,              
    -- Auditoría
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_ENTREGA_RENDIR (
    ID_FONDO NUMBER PRIMARY KEY, 
    MOTIVO_ENTREGA_RENDIR VARCHAR2(200),
    MONTO_SOLICITADO NUMBER(10,2),
    FECHA_SOLICITUD DATE,
    FECHA_APERTURA DATE,
    FECHA_CIERRE DATE,
    ESTADO_ENTREGA VARCHAR2(20),
    
    ID_SOLICITANTE NUMBER,       
    ID_APROBADOR NUMBER,
    
    ID_RENDICION NUMBER, 
    
    -- Auditoría
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

-- =============================================
-- 5. OPERATIVA DE CAJA CHICA (CICLO Y SOLICITUDES)
-- =============================================

CREATE TABLE CC_CICLO_CAJA (
    ID_CICLO_CAJA NUMBER PRIMARY KEY,
    NUMERO_SEMANA_CICLO_CAJA VARCHAR2(20),
    FECHA_APERTURA_CICLO_CAJA DATE,
    FECHA_CIERRE_CICLO_CAJA DATE,
    MONTO_TECHO_CICLO_CAJA NUMBER(10,2),
    SALDO_INICIAL_CICLO_CAJA NUMBER(10,2),
    TOTAL_GASTADO_CICLO_CAJA NUMBER(10,2),
    ESTADO_CICLO_CAJA VARCHAR2(20),
    ID_CAJA_CHICA NUMBER,
    
    -- El Ciclo se rinde completo
    ID_RENDICION NUMBER,
    
    -- Auditoría
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

CREATE TABLE CC_SOLICITUD_GASTO (
    ID_SOLICITUD_GASTO NUMBER PRIMARY KEY,
    FECHA_SOLICITUD_GASTO DATE, 
    MONTO_SOLICITUD_GASTO NUMBER(10,2),
    MOTIVO_SOLICITUD_GASTO VARCHAR2(200),
    ESTADO_SOLICITUD_GASTO VARCHAR2(20),
    
    ID_SOLICITANTE NUMBER,       
    ID_CICLO_CAJA NUMBER,        
    
    -- SIN ID_RENDICION (La rendición es por Ciclo)
    
    -- Auditoría
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

-- =============================================
-- 6. COMPROBANTES (EVIDENCIA DE GASTO)
-- =============================================

CREATE TABLE CC_COMPROBANTE_PAGO (
    ID_COMPROBANTE NUMBER PRIMARY KEY,
    TIPO_DOCUMENTO VARCHAR2(20),
    RUC_PROVEEDOR CHAR(11),
    RAZON_SOCIAL VARCHAR2(150),
    NUMERO_SERIE VARCHAR2(30),
    FECHA_EMISION DATE,
    MONTO_TOTAL NUMBER(10,2),
    SUBTOTAL NUMBER(10,2),
    IGV NUMBER(10,2),
    ARCHIVO_ADJUNTO VARCHAR2(255),
    
    -- Relación Dual
    ID_SOLICITUD_GASTO NUMBER,   
    ID_ENTREGA_RENDIR NUMBER,    
    
    ID_RUBRO NUMBER,             
    ID_MONEDA NUMBER,            
    -- Auditoría
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);

-- =============================================
-- 7. MOVIMIENTOS DE DINERO
-- =============================================

CREATE TABLE CC_TRANSACCION (
    ID_TRANSACCION NUMBER PRIMARY KEY,
    TIPO_OPERACION VARCHAR2(30),
    FECHA_OPERACION DATE,
    MONTO_TRANSACCION NUMBER(10,2),
    NUMERO_OPERACION_BANCARIA VARCHAR2(30),
    MEDIO_PAGO VARCHAR2(30),
    TIPO_CAMBIO NUMBER(10,4),
    ID_CUENTA_ORIGEN NUMBER,     
    ID_CUENTA_DESTINO NUMBER,    
    ID_MONEDA NUMBER,            
    -- Auditoría
    USUARIO_CREACION VARCHAR2(50),
    FECHA_CREACION DATE,
    USUARIO_MODIFICACION VARCHAR2(50),
    FECHA_MODIFICACION DATE
);


/* =========================================================
   SCRIPT DE CONSTRAINTS (FOREIGN KEYS)
   ========================================================= */

-- 1. Empleados
ALTER TABLE CC_EMPLEADO ADD CONSTRAINT FK_EMPLEADO_AREA FOREIGN KEY (ID_AREA) REFERENCES CC_AREA(ID_AREA);
ALTER TABLE CC_EMPLEADO ADD CONSTRAINT FK_EMPLEADO_ROL FOREIGN KEY (ID_ROL) REFERENCES CC_ROL(ID_ROL);
ALTER TABLE CC_EMPLEADO ADD CONSTRAINT FK_EMPLEADO_JEFE FOREIGN KEY (ID_JEFE_DIRECTO) REFERENCES CC_EMPLEADO(ID_EMPLEADO);

-- 2. Cuentas
ALTER TABLE CC_CUENTA_BANCARIA ADD CONSTRAINT FK_CUENTA_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES CC_EMPLEADO(ID_EMPLEADO);
ALTER TABLE CC_CUENTA_BANCARIA ADD CONSTRAINT FK_CUENTA_MONEDA FOREIGN KEY (ID_MONEDA) REFERENCES CC_MONEDA(ID_MONEDA);

-- 3. Fondos (Padre e Hijos)
ALTER TABLE CC_FONDO ADD CONSTRAINT FK_FONDO_MONEDA FOREIGN KEY (ID_MONEDA) REFERENCES CC_MONEDA(ID_MONEDA);
ALTER TABLE CC_FONDO ADD CONSTRAINT FK_FONDO_CUENTA FOREIGN KEY (ID_CUENTA_BANCARIA) REFERENCES CC_CUENTA_BANCARIA(ID_CUENTA_BANCARIA);
ALTER TABLE CC_FONDO ADD CONSTRAINT FK_FONDO_RESPONSABLE FOREIGN KEY (ID_RESPONSABLE) REFERENCES CC_EMPLEADO(ID_EMPLEADO);

ALTER TABLE CC_CAJA_CHICA ADD CONSTRAINT FK_CAJA_FONDO_PADRE FOREIGN KEY (ID_FONDO) REFERENCES CC_FONDO(ID_FONDO);
ALTER TABLE CC_CAJA_CHICA ADD CONSTRAINT FK_CAJA_AREA FOREIGN KEY (ID_AREA) REFERENCES CC_AREA(ID_AREA);

ALTER TABLE CC_ENTREGA_RENDIR ADD CONSTRAINT FK_ENTREGA_FONDO_PADRE FOREIGN KEY (ID_FONDO) REFERENCES CC_FONDO(ID_FONDO);
ALTER TABLE CC_ENTREGA_RENDIR ADD CONSTRAINT FK_ENTREGA_SOLICITANTE FOREIGN KEY (ID_SOLICITANTE) REFERENCES CC_EMPLEADO(ID_EMPLEADO);
ALTER TABLE CC_ENTREGA_RENDIR ADD CONSTRAINT FK_ENTREGA_APROBADOR FOREIGN KEY (ID_APROBADOR) REFERENCES CC_EMPLEADO(ID_EMPLEADO);

-- Relación: Entrega -> Rendición
ALTER TABLE CC_ENTREGA_RENDIR ADD CONSTRAINT FK_ENTREGA_RENDICION FOREIGN KEY (ID_RENDICION) REFERENCES CC_RENDICION(ID_RENDICION);

-- 4. Ciclo de Caja
ALTER TABLE CC_CICLO_CAJA ADD CONSTRAINT FK_CICLO_CAJA_PADRE FOREIGN KEY (ID_CAJA_CHICA) REFERENCES CC_CAJA_CHICA(ID_FONDO);
-- Relación Ciclo -> Rendición
ALTER TABLE CC_CICLO_CAJA ADD CONSTRAINT FK_CICLO_RENDICION FOREIGN KEY (ID_RENDICION) REFERENCES CC_RENDICION(ID_RENDICION);

-- 5. Solicitud de Gasto (Caja Chica)
ALTER TABLE CC_SOLICITUD_GASTO ADD CONSTRAINT FK_SOLICITUD_EMPLEADO FOREIGN KEY (ID_SOLICITANTE) REFERENCES CC_EMPLEADO(ID_EMPLEADO);
ALTER TABLE CC_SOLICITUD_GASTO ADD CONSTRAINT FK_SOLICITUD_CICLO FOREIGN KEY (ID_CICLO_CAJA) REFERENCES CC_CICLO_CAJA(ID_CICLO_CAJA);

-- 6. Comprobantes (Documentos de Gasto)
ALTER TABLE CC_COMPROBANTE_PAGO ADD CONSTRAINT FK_COMPROBANTE_RUBRO FOREIGN KEY (ID_RUBRO) REFERENCES CC_RUBRO(ID_RUBRO);
ALTER TABLE CC_COMPROBANTE_PAGO ADD CONSTRAINT FK_COMPROBANTE_MONEDA FOREIGN KEY (ID_MONEDA) REFERENCES CC_MONEDA(ID_MONEDA);

ALTER TABLE CC_COMPROBANTE_PAGO ADD CONSTRAINT FK_COMPROBANTE_SOLICITUD FOREIGN KEY (ID_SOLICITUD_GASTO) REFERENCES CC_SOLICITUD_GASTO(ID_SOLICITUD_GASTO);
ALTER TABLE CC_COMPROBANTE_PAGO ADD CONSTRAINT FK_COMPROBANTE_ENTREGA FOREIGN KEY (ID_ENTREGA_RENDIR) REFERENCES CC_ENTREGA_RENDIR(ID_FONDO);

-- 7. Transacciones
ALTER TABLE CC_TRANSACCION ADD CONSTRAINT FK_TRANSACCION_CTA_ORIGEN FOREIGN KEY (ID_CUENTA_ORIGEN) REFERENCES CC_CUENTA_BANCARIA(ID_CUENTA_BANCARIA);
ALTER TABLE CC_TRANSACCION ADD CONSTRAINT FK_TRANSACCION_CTA_DESTINO FOREIGN KEY (ID_CUENTA_DESTINO) REFERENCES CC_CUENTA_BANCARIA(ID_CUENTA_BANCARIA);
ALTER TABLE CC_TRANSACCION ADD CONSTRAINT FK_TRANSACCION_MONEDA FOREIGN KEY (ID_MONEDA) REFERENCES CC_MONEDA(ID_MONEDA);

--Historial de empleados
ALTER TABLE CC_HISTORIAL_JEFATURA ADD CONSTRAINT PK_HIST_JEFATURA PRIMARY KEY (ID_HISTORIAL);
ALTER TABLE CC_HISTORIAL_JEFATURA ADD CONSTRAINT FK_HIST_EMP FOREIGN KEY (ID_EMPLEADO) REFERENCES CC_EMPLEADO(ID_EMPLEADO);
ALTER TABLE CC_HISTORIAL_JEFATURA ADD CONSTRAINT FK_HIST_JEFE FOREIGN KEY (ID_JEFE) REFERENCES CC_EMPLEADO(ID_EMPLEADO);

