-- =============================================
-- SCRIPT DE LIMPIEZA (DROP TABLE)
-- Elimina tablas y sus restricciones asociadas
-- =============================================

-- 1. Eliminar Tablas Transaccionales (Detalle más bajo)
DROP TABLE CC_TRANSACCION CASCADE CONSTRAINTS;
DROP TABLE CC_COMPROBANTE_PAGO CASCADE CONSTRAINTS;

-- 2. Eliminar Núcleo Operativo (Solicitudes y Rendiciones)
-- Al usar CASCADE CONSTRAINTS, no importa si Solicitud apunta a Rendición o viceversa.
DROP TABLE CC_SOLICITUD_GASTO CASCADE CONSTRAINTS;
DROP TABLE CC_RENDICION CASCADE CONSTRAINTS;

-- 3. Eliminar Ciclos y Subtipos de Fondo
DROP TABLE CC_CICLO_CAJA CASCADE CONSTRAINTS;
DROP TABLE CC_ENTREGA_RENDIR CASCADE CONSTRAINTS;
DROP TABLE CC_CAJA_CHICA CASCADE CONSTRAINTS;

-- 4. Eliminar Fondo Padre y Cuentas
DROP TABLE CC_FONDO CASCADE CONSTRAINTS;
DROP TABLE CC_CUENTA_BANCARIA CASCADE CONSTRAINTS;

-- 5. Eliminar Personal
DROP TABLE CC_EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE CC_HISTORIAL_JEFATURA CASCADE CONSTRAINTS;
-- 6. Eliminar Tablas Maestras (Catálogos)
DROP TABLE CC_ROL CASCADE CONSTRAINTS;
DROP TABLE CC_AREA CASCADE CONSTRAINTS;
DROP TABLE CC_RUBRO CASCADE CONSTRAINTS;
DROP TABLE CC_MONEDA CASCADE CONSTRAINTS;

-- (Opcional) Limpiar papelera de reciclaje de Oracle para liberar nombres
PURGE RECYCLEBIN;