/* =========================================================
   SCRIPT DE TRIGGERS FINAL - AUDITORÍA Y VALORES POR DEFECTO
   - Lógica optimizada: Modificación se guarda SIEMPRE (Insert o Update).
   - Creación solo en INSERT.
   - Valores por defecto (0 en vez de NULL) solo en INSERT.
   - Evento DELETE removido (no requerido).
   ========================================================= */

-- 1. TABLA: CC_MONEDA
CREATE OR REPLACE TRIGGER TRG_CC_MONEDA
BEFORE INSERT OR UPDATE ON CC_MONEDA
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION   := SYSDATE;
    END IF;

    -- Se ejecuta siempre (en Insert o Update) para guardar el último rastro
    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION   := SYSDATE;
END;
/

-- 2. TABLA: CC_RUBRO
CREATE OR REPLACE TRIGGER TRG_CC_RUBRO
BEFORE INSERT OR UPDATE ON CC_RUBRO
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION   := SYSDATE;
    END IF;

    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION   := SYSDATE;
END;
/

-- 3. TABLA: CC_AREA
CREATE OR REPLACE TRIGGER TRG_CC_AREA
BEFORE INSERT OR UPDATE ON CC_AREA
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION   := SYSDATE;
    END IF;

    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION   := SYSDATE;
END;
/

-- 4. TABLA: CC_ROL
CREATE OR REPLACE TRIGGER TRG_CC_ROL
BEFORE INSERT OR UPDATE ON CC_ROL
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION   := SYSDATE;
    END IF;

    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION   := SYSDATE;
END;
/

-- 5. TABLA: CC_EMPLEADO
CREATE OR REPLACE TRIGGER TRG_CC_EMPLEADO
BEFORE INSERT OR UPDATE ON CC_EMPLEADO
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION   := SYSDATE;
    END IF;

    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION   := SYSDATE;
END;
/

-- 6. TABLA: CC_CUENTA_BANCARIA
CREATE OR REPLACE TRIGGER TRG_CC_CUENTA_BANCARIA
BEFORE INSERT OR UPDATE ON CC_CUENTA_BANCARIA
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION   := SYSDATE;
        -- Valor por defecto
        :NEW.ES_CUENTA_BANCARIA_PRINCIPAL := NVL(:NEW.ES_CUENTA_BANCARIA_PRINCIPAL, 0);
    END IF;

    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION   := SYSDATE;
END;
/

-- 7. TABLA: CC_RENDICION
CREATE OR REPLACE TRIGGER TRG_CC_RENDICION
BEFORE INSERT OR UPDATE ON CC_RENDICION
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION   := SYSDATE;
        -- Inicializar montos a 0
        :NEW.TOTAL_DECLARADO := NVL(:NEW.TOTAL_DECLARADO, 0);
        :NEW.TOTAL_APROBADO  := NVL(:NEW.TOTAL_APROBADO, 0);
        :NEW.SALDO_FINAL     := NVL(:NEW.SALDO_FINAL, 0);
    END IF;

    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION   := SYSDATE;
END;
/

-- 8. TABLA: CC_FONDO
CREATE OR REPLACE TRIGGER TRG_CC_FONDO
BEFORE INSERT OR UPDATE ON CC_FONDO
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION   := SYSDATE;
        -- Inicializar saldo
        :NEW.SALDO_ACTUAL_FONDO := NVL(:NEW.SALDO_ACTUAL_FONDO, 0);
    END IF;

    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION   := SYSDATE;
END;
/

-- 9. TABLA: CC_CAJA_CHICA
CREATE OR REPLACE TRIGGER TRG_CC_CAJA_CHICA
BEFORE INSERT OR UPDATE ON CC_CAJA_CHICA
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION   := SYSDATE;
        -- Inicializar techo
        :NEW.MONTO_TECHO_CAJA_CHICA := NVL(:NEW.MONTO_TECHO_CAJA_CHICA, 0);
    END IF;

    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION   := SYSDATE;
END;
/

-- 10. TABLA: CC_ENTREGA_RENDIR
CREATE OR REPLACE TRIGGER TRG_CC_ENTREGA_RENDIR
BEFORE INSERT OR UPDATE ON CC_ENTREGA_RENDIR
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION   := SYSDATE;
        -- Inicializar monto solicitado
        :NEW.MONTO_SOLICITADO := NVL(:NEW.MONTO_SOLICITADO, 0);
    END IF;

    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION   := SYSDATE;
END;
/

-- 11. TABLA: CC_CICLO_CAJA
CREATE OR REPLACE TRIGGER TRG_CC_CICLO_CAJA
BEFORE INSERT OR UPDATE ON CC_CICLO_CAJA
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION   := SYSDATE;
        -- Inicializar montos operativos
        :NEW.MONTO_TECHO_CICLO_CAJA   := NVL(:NEW.MONTO_TECHO_CICLO_CAJA, 0);
        :NEW.SALDO_INICIAL_CICLO_CAJA := NVL(:NEW.SALDO_INICIAL_CICLO_CAJA, 0);
        :NEW.TOTAL_GASTADO_CICLO_CAJA := NVL(:NEW.TOTAL_GASTADO_CICLO_CAJA, 0);
    END IF;

    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION   := SYSDATE;
END;
/

-- 12. TABLA: CC_SOLICITUD_GASTO
CREATE OR REPLACE TRIGGER TRG_CC_SOLICITUD_GASTO
BEFORE INSERT OR UPDATE ON CC_SOLICITUD_GASTO
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION   := SYSDATE;
        -- Inicializar monto
        :NEW.MONTO_SOLICITUD_GASTO := NVL(:NEW.MONTO_SOLICITUD_GASTO, 0);
    END IF;

    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION   := SYSDATE;
END;
/

-- 13. TABLA: CC_COMPROBANTE_PAGO
CREATE OR REPLACE TRIGGER TRG_CC_COMPROBANTE_PAGO
BEFORE INSERT OR UPDATE ON CC_COMPROBANTE_PAGO
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION   := SYSDATE;
        -- Inicializar montos financieros
        :NEW.MONTO_TOTAL := NVL(:NEW.MONTO_TOTAL, 0);
        :NEW.SUBTOTAL    := NVL(:NEW.SUBTOTAL, 0);
        :NEW.IGV         := NVL(:NEW.IGV, 0);
    END IF;

    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION   := SYSDATE;
END;
/

-- 14. TABLA: CC_TRANSACCION
CREATE OR REPLACE TRIGGER TRG_CC_TRANSACCION
BEFORE INSERT OR UPDATE ON CC_TRANSACCION
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION   := SYSDATE;
        -- Inicializar monto
        :NEW.MONTO_TRANSACCION := NVL(:NEW.MONTO_TRANSACCION, 0);
    END IF;

    :NEW.USUARIO_MODIFICACION := USER;
    :NEW.FECHA_MODIFICACION   := SYSDATE;
END;
/
--15.
CREATE OR REPLACE TRIGGER TRG_CONTROL_HISTORIAL_JEFES
AFTER INSERT OR UPDATE OF ID_JEFE_DIRECTO ON CC_EMPLEADO
FOR EACH ROW
BEGIN
    -- PARTE A: Cerrar el ciclo del jefe anterior (Update fecha fin)
    -- Solo si estamos actualizando y el empleado tenía un jefe previo
    IF UPDATING AND :OLD.ID_JEFE_DIRECTO IS NOT NULL THEN
        UPDATE CC_HISTORIAL_JEFATURA
        SET FECHA_FIN = SYSDATE
        WHERE ID_EMPLEADO = :OLD.ID_EMPLEADO 
          AND FECHA_FIN IS NULL; -- Importante: Cerrar solo el registro vigente
    END IF;

    -- PARTE B: Abrir el nuevo ciclo con el nuevo jefe
    -- Se inserta siempre que hay un cambio o un nuevo empleado
    -- Nota: Si ID_JEFE_DIRECTO es NULL (Gerente), se guarda el histórico indicando NULL (sin jefe)
    INSERT INTO CC_HISTORIAL_JEFATURA (
        ID_HISTORIAL, ID_EMPLEADO, ID_JEFE, FECHA_INICIO, FECHA_FIN
    ) VALUES (
        (SELECT NVL(MAX(ID_HISTORIAL), 0) + 1 FROM CC_HISTORIAL_JEFATURA), -- Generador ID
        :NEW.ID_EMPLEADO,
        :NEW.ID_JEFE_DIRECTO,
        SYSDATE, -- Fecha Inicio es AHORA
        NULL     -- Fecha Fin queda abierta
    );
END;
/